# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      # First yml action
      - name: Jekyll Actions
          # You may pin to the exact commit or the version.
          # uses: helaili/jekyll-action@57a6a260778ffcec2b3ffb312f6e515e14e9fe62
          uses: helaili/jekyll-action@2.0.4
          with:
            target_branch: public
